function [Temp,Xmelt]=Cal_Temp_V_Si14(...
    logrho,depth,Cwbulk,Dpartition,Cc,...
    Threshold,Xol,Xopx,Xcpx,Xgrt,...
    Dsolidol,Dsolidopx,Dsolidcpx,Dsolidgrt,...
    Dmixol,Dmixopx,Dmixcpx,Dmixgrt,Dmixmelt)
    %Tsigma_Cal_Temp

Y=@(T)log10(1/BULK(T,depth,Cwbulk,Dpartition,Cc,Threshold,...
    Xol,Xopx,Xcpx,Xgrt,...
    Dsolidol,Dsolidopx,Dsolidcpx,Dsolidgrt,...
    Dmixol,Dmixopx,Dmixcpx,Dmixgrt,Dmixmelt))-logrho;
Temp=fsolve(Y,0);

meltT=Tempmelt(depth,Cwbulk,Dpartition);
if Temp<=meltT 
    Xmelt=0;
else
    Xmelt=Fmelt(Temp,depth,Cwbulk,Dpartition)*100;
end